name: cleanup

on:
  schedule:
    # Runs at 02:00 on the 1st of every month
    - cron: "0 2 1 * *"
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  packages: write  # Required to delete GHCR images

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      OWNER: ${{ github.repository_owner }}
      PACKAGE_NAME: embedding-models-api

    steps:
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'embedding-models-api'
        package-type: 'container'
        min-versions-to-keep: 3
